export enum DownloadObsDataEnum {
  parcelle = "Parcelle",
  rosier = "Rosier",
  hauteur = "Hauteur",
  position = "Position",
  date = "Date",
  stade_pheno = "Stade phénologique",
  nb_total_feuilles = "Nb total feuilles",
  nb_feuilles_rouille = "Nb feuilles rouille",
  freq_rouille = "Fréquence rouille",
  int_rouille = "Intensité rouille",
  nb_feuilles_ecidies = "Nb feuilles ecidies",
  freq_ecidies = "Fréquence ecidies",
  nb_feuilles_uredos = "Nb feuilles uredos",
  freq_uredos = "Fréquence uredos",
  nb_feuilles_teleutos = "Nb feuilles téléutos",
  freq_teleutos = "Fréquence téléutos",
  nb_feuilles_marsonia = "Nb feuilles marsonia",
  freq_marsonia = "Fréquence marsonia",
  commentaire = "Commentaire",
}
