export enum StadePhenosEnum {
  N_00 = "00 - Repos hivernal ou dormance",
  N_01 = "01 - Début gonflement des bourgeons",
  N_03 = "03 - Fin gonflement des bourgeons",
  N_07 = "07 - Début débourrement",
  N_09 = "09 - Débourrement",
  N_10 = "10 - Première feuille étalée",
  N_13 = "13 - Trois feuilles étalées",
  N_15 = "15 - Cinq feuilles étalées",
  N_19 = "19 - Neuf ou plus feuilles étalées",
  N_31 = "31 - Début croissance des pousses",
  N_35 = "35 - Croissance active des pousses",
  N_39 = "39 - Fin croissance des pousses",
  N_61 = "61 - Début floraison",
  N_65 = "65 - Pleine floraison",
  N_69 = "69 - Fin floraison",
  N_91 = "91 - Fin croissance rameaux",
  N_92 = "92 - Début décoloration des feuilles",
  N_93 = "93 - Début chute des feuilles",
  N_95 = "95 - Chute active des feuilles",
  N_97 = "97 - Fin chute des feuilles",
}
